### ISSUE TITLE
Forecasts no longer work

### ISSUE THREAD

**Issue by brainrecall** [vche/appdaemon_weatherentity#14]
Hi, thanks for this awesome widget. It's been a great addition, since the default AppDaemon weather widget is still stuck using the non-free Dark Sky API. Just pointing to a weather entity on HA is a smart choice and decouples the dependency.

Unfortunately, HA made some recent changes in 2024.04 and now weather forecasts are no longer attributes on the entity. They must be accessed by a service call, https://www.home-assistant.io/integrations/weather/#service-weatherget_forecasts

I'm not sure if AppDaemon can directly call a service like that, if not it might require something like a timed template or other automation to populate a different entity with the forecast data.

Has there been any work or thought on getting forecasts working again?

**Comment by vche** [comment]
Hi, thanks for raising this. I'm not using this anymore, so no i wasn't aware nor did I think of anything, but i'll try to have a look as soon as i can free up some time. 

If you're willing to contribute you're also welcome

**Comment by vche** [comment]
### Problem
- As pointed out by brainrecall, forecast information have been removed from the homeassistant weather entity and now need to be fetched by [callling a service](https://www.home-assistant.io/integrations/weather/#service-weatherget_forecasts)
- This service is returning data, which is a new feature for service calls. This is only supported in websockets API and not REST API, and [there are no plan to support this](https://github.com/home-assistant/core/issues/106379#issuecomment-18785481240)
- Appdaemon currently only supports REST API, plans seems to be in place to support websockets [the code shows some preparation](https://github.com/AppDaemon/appdaemon/blob/69205a1dc90fd65c72894b802fc396f052c99d28/appdaemon/plugins/hass/hassplugin.py#L510) (see [this commit](https://github.com/AppDaemon/appdaemon/commit/c82866a5b8b56a95f3c5f6b10bdafa062a5d9b30)) but as of now it is not released.
- The change to websockets will be implemented as [per this open issue](https://github.com/AppDaemon/appdaemon/issues/1837). It also provide a potential workaround

### Solution
- Long term solution is to call the websocket api and set `return_response` 
- Short term solution, there are 2 possibilities:
  - Using scheduled template calls
  - Using a script wrapper
 
I'll compare them when i can and push a fix

**Comment by clews** [comment]
For the impatient: I fixed this temporarily by using a triggered template like the one mentioned here:

https://github.com/home-assistant/core/issues/112628#issuecomment-1986196691

It works for me (replacing weather.home with sensor.weather_hourly in my dashboard widget) and it also works for daily forecast (replacing hourly by daily, i made a second template to have both):

No patch needed on the appdaemon widget for this workaround.

**Comment by mad-ady** [comment]
@clews thanks for pointing out the workaround. Indeed, it has worked for me as well!

One (slightly off-topic) question - you mention you're using a daily forecast template too. I'm using OpenWeatherMap, which doesn't provide daily forecasts, only hourly. Which weather provider are you using, or if using OpenWeatherMap, how are you getting daily forecasts out of it?

Thanks!

**Comment by brainrecall** [comment]
Thanks @clews I was able to get it working again! I'm using a template to recreate the legacy weather entity from OpenWeatherMap, with the daily forecast. This should work for you @mad-ady 

```
template:
  - trigger:
      - platform: time_pattern
        hours: /1
      - platform: homeassistant
        event: start
    action:
      - service: weather.get_forecasts
        data:
          type: daily
        target:
          entity_id: weather.openweathermap
        response_variable: daily
    sensor:
      - name: Weather Daily
        state: "{{ states('weather.openweathermap') }}"
        attributes:
          temperature: "{{ state_attr('weather.openweathermap', 'temperature') }}"
          dew_point: "{{ state_attr('weather.openweathermap', 'dew_point') }}"
          temperature_unit: "{{ state_attr('weather.openweathermap', 'temperature_unit') }}"
          humidity: "{{ state_attr('weather.openweathermap', 'humidity') }}"
          cloud_coverage: "{{ state_attr('weather.openweathermap', 'cloud_coverage') }}"
          pressure: "{{ state_attr('weather.openweathermap', 'pressure') }}"
          pressure_unit: "{{ state_attr('weather.openweathermap', 'pressure_unit') }}"
          wind_bearing: "{{ state_attr('weather.openweathermap', 'wind_bearing') }}"
          wind_speed: "{{ state_attr('weather.openweathermap', 'wind_speed') }}"
          wind_speed_unit: "{{ state_attr('weather.openweathermap', 'wind_speed_unit') }}"
          visibility_unit: "{{ state_attr('weather.openweathermap', 'visibility_unit') }}"
          precipitation_unit: "{{ state_attr('weather.openweathermap', 'precipitation_unit') }}"
          forecast: "{{ daily['weather.openweathermap'].forecast }}"
```

Note that I had to restart AppDaemon after adding the template. Then Set the dashboard entity to `sensor.weather_daily`

```
openweathermap:
    title: Now
    widget_type: weatherentity
    entity: sensor.weather_daily
    show_forecast: 3
    forecast_daily: 1
    prefer_icons: 1
    unit: "&deg;F"
    wind_unit: "mph"
    pressure_unit: "hPa"
    rain_unit: "%"
    forecast_precip_unit: "in"
```
