### ISSUE TITLE
entities

### ISSUE THREAD

**Issue by Sborkahome** [vche/appdaemon_weatherentity#3]
Good day! Tell me, please, how to set the parameters for "entities:" correctly? 
That's not how it works:

entities: 
  temperature: sensor.openweathermap_temperature
  humidity: sensor.openweathermap_humidity

**Comment by vche** [comment]
Hi,

I assume you're talking about the appdaemon dashboard configuration.
First this is a yaml file, so you need indentation, your example wouldn't work like that.
Then refer to the [main widget documentation for examples](https://appdaemon.readthedocs.io/en/latest/DASHBOARD_CREATION.html#weather) to use sensors, I believe the entities was changed to sensor.

Here's my own configuration that doesn't use sensors but the normal widget:
```
weather:
  title: Now
  widget_type: weatherentity
  entity: weather.openweathermap
  show_forecast: 4
  forecast_daily: 1
  prefer_icons: 1
  # Units as configured in homeassistant
  units: "&deg;C"
  wind_unit: "km/h"
  pressure_unit: "hPa"
  rain_unit: "%"
```
